#!/usr/bin/env bash
# Write a Bash script that pings an IP address passed as an argument.

# Check if an IP address is provided as an argument
if [[ -z $1 ]]; then
	echo "Usage: $0 {IP_ADDRESS}"
	exit 1
fi

# Perform ping to the specified IP address
ping -c 5 "$1"
